### ISSUE TITLE
Add additional Rubocop gems

### ISSUE THREAD

**Issue by chiefpansancolt** [andrewmcodes/haml-lint-action#4]
# Bug Report 
get and error when running haml-lint when rubocop.yml file has rubocop-rails or other styles causes it to error but not fail. Be nice to ensure that there is all rubocop gems available to not error when reading the rubocop.yml file.

**Comment by andrewmcodes** [comment]
@chiefpansancolt here's a question for you, I can either allow the user to input additional gems to install (ie rubocop-rails), or I can just tell the action to bundle the gemfile instead. Bundling will certainly take longer in most cases, but I am down to maybe just offer it as an option.

ex:
```yaml
name: HAML Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: HAML Lint
      uses: andrewmcodes/haml-lint-action@v0.0.1
      with:
          bundle: true # example with bundle option
          additional_gems: 'rubocop-rails rubocop-minitest' # example with option to add additional gems
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Feel free to ping me on Twitter if you want to chat back and forth about this, I would welcome some input!

While you're here, I found a bug that I am sure you will run across:
If you are running to checks in the same suite, you cannot actually associate the runs correctly. See an example [here](https://github.com/andrewmcodes/rubocop-linter-action-test/runs/293423014). This is a GitHub bug though and I cannot do anything about it unfortunately. I have been monitoring [this](https://github.community/t5/GitHub-Actions/Github-Actions-Status-Checks-created-on-incorrect-Check-Suite-Id/m-p/36180) forum post for updates.
